stages:
  - test
  - release

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

cache:
  key: "$CI_PROJECT_NAME-CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules

backend-test:
  stage: test
  cache:
    paths:
      - backend/deps
  script:
    - cd backend; make test


release:
  stage: release
  script:
    - make release
  artifacts:
    paths:
      - serverboards.tar.gz
    expire_in: 1 week
