stages:
  - test
  - release

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

cache:
  key: "$CI_PROJECT_NAME-$CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules


backend-test:
  stage: test
  script:
    - cd backend
    - pwd
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.clean --all
    - mix deps.get
    - MIX_ENV=test mix deps.compile
    - mix test

frontend-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - cd frontend
    - pwd
    - yarn
    - npm test

release:
  stage: release
  script:
    - cd $CI_PROJECT_DIR
    - make release
  artifacts:
    paths:
      - serverboards.tar.gz
    expire_in: 1 week
  only:
    - master

release-debian:
  stage: release
  script:
    - make deb
  artifacts:
    paths:
      - serverboards.deb
    expire_in: 1 week
#  only:
#    - master