stages:
  - test
  - release
  - publish

variables:
  GIT_STRATEGY: fetch

cache:
  key: "$CI_PROJECT_NAME-$CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules


backend-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - scripts/backend-test.sh
  artifacts:
    paths:
      - log
    expire_in: 1 week

frontend-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - cd frontend
    - pwd
    - yarn
    - npm test

plugins-test:
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - scripts/plugin-test.sh

release:
  stage: release
  script:
    - scripts/version-update.sh
    - make deb
  tags:
    - ubuntu1604
  artifacts:
    paths:
      - serverboards.deb
    expire_in: 1 week
  only:
    - master
    - CORE-4-unstable-deb-channel

publish:
  stage: publish
  script:
    - sudo -H /usr/local/bin/publish-unstable
  dependencies:
    - release
  variables:
    DEBSIGN_KEYID: C1FCABC2
  tags:
    - ubuntu1604
    - rsync-www
  only:
    - master
    - CORE-4-unstable-deb-channel
