stages:
  - test
  - release

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

cache:
  key: "$CI_PROJECT_NAME"
  untracked: true
  paths:
    - frontend/dist
    - frontend/node_modules
    - backend/deps
    - backend/mix.lock
    - backend/_build

backend-test:
  stage: test
  cache:
    paths:
      - backend/deps
  script:
    - cd backend; make test


release:
  stage: release
  script:
    - make release
  artifacts:
    paths:
      - serverboards.tar.gz
    expire_in: 1 week
