stages:
  - test
  - release

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

cache:
  key: "$CI_PROJECT_NAME-CI_BUILD_REF_NAME"
  paths:
    - frontend/node_modules

before_script:
  - cd backend
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get

backend-test:
  stage: test
  cache:
    paths:
      - backend/_build
      - backend/deps

  script:
    - mix test


release:
  stage: release
  script:
    - cd $CI_PROJECT_DIR
    - make release
  artifacts:
    paths:
      - serverboards.tar.gz
    expire_in: 1 week
